### ISSUE TITLE
Jeedom integration

### ISSUE THREAD

**Issue by tiico0** [rene-d/wifinfo#20]
Code for jeedom integration is not working due to change of Teleinfo plugin (Jeedom) : POST method now
Is it possible to adapt the code to create a version with jeedom compatibility?

https://nextdom.github.io/plugin-teleinfo/fr_FR/#tocAnchor-1-14

**Comment by rene-d** [comment]
You can easily adapt the code to forge the adequate Jeedom request. However, I won't do the modification, since I don't use Jeedom and I have no way to test it.
See https://github.com/rene-d/wifinfo/blob/e91efa7b8b4d42737801e5a0465a3f8f25a5dc1c/src/tic.cpp#L363 for an example to make a HTTP POST request.

**Comment by tiico0** [comment]
thanks. 
I have found that solution and modify it locally.
Regards

**Comment by rene-d** [comment]
Ok. You can PR if you dare :)
